### ISSUE TITLE
[Bike Shop] Empty page while list of products is loading

### ISSUE THREAD

**Issue by aghassemi** [ampproject/ampstart#754]
While the list of products is loading in Bike Shop, user sees whitespace. We should see what we can do to make this UX better. 

Couple of options I can think of that involves using `amp-state` binding with `amp-list` instead of list doing the query, in this approach we can either:

1- Have some initial inlined stale data in `amp-state` which will render the list immediately. Have the `amp-state` do the XHR to update the state and mutate the list. @choumx this assumes that `amp-list` binding with `amp-state` runs on page load and mutation after `amp-state` fetches data from an endpoint also happens at pageload, from what I remember, both these should happen since `amp-list` is special cased to allow onload mutations, is this correct?

2- similar to (1) but instead of real state data, have some placeholder data (about the same number of items the list is expected to get back)

@camelburrito @spacedino @ericlindley-g 

could be a good one to discuss in design review as well.

**Comment by ericlindley-g** [comment]
+1 I've been thinking about this same thing (getting similar issues in the travel template, as well as with several sites online who are adopting, and it's come up recently with folks who work with developers wondering what to recommend). I would love for us to develop and implement clear pathways to good UX here (and make these patterns clear to external developers)

I like the methods you're proposing. One potential issue is having the content shuffle after load, so here's another possible route:

1. If your sortable/filterable content takes up most of the page (e.g. product listings) and is unlikely to be highly dynamic, use a placeholder with real content and *don't update on load*—wait for user interaction to trigger sorting/filtering/etc

2. If your content takes up most of the page and is highly dynamic (so a placeholder would change significantly at load: don't convert this page to AMP  (though this is somewhat provocative and I'm not sure I fully think this is the right way to go, I want to consider that this could be the recommendation. If we didn't want to be this prohibitive in our recommendation, I think 1 or 2 above are good options, and I'd be curious to hear more discussion before we nail something down)

3. If your dynamic content only takes up bits and pieces of the page (updating price and inventory, but not whole blocks of content). Just use amp-list and have a reasonable placeholder, but don't worry about it changing at load time.


I'm not sure these practices could be meaningfully enforced, but would help guide the types of implementations we put out there.

**Comment by aghassemi** [comment]
related bug: https://github.com/ampproject/amphtml/issues/11998

**Comment by lswang1618** [comment]
I think there's two things to consider - first, that a site should really only be using amp-list for data that is actually highly dynamic. Otherwise they can rely on stale-and-revalidate model and update-cache pings for the long-tail. Or I could imagine cases where the product list itself is not changing that often, but things like price and variant availability are - in which case they could just use amp-list to fetch those attributes. 

Under this recommendation, if a site is using amp-list for most of the page, i.e. product listings, they're changing often enough that a placeholder could lead to an experience where a user may see a product they like which disappears after the fresh content is retrieved. So I'm not super sure that a placeholder makes the most sense. 

For a partner in Latam, we upped the update cache ping quota so that they could server side render and still be comfortable with the freshness of the data. But if we decide this isn't really a best practice, then I think the second recommendation Eric mentioned would make sense.

**Comment by camelburrito** [comment]
Sometimes we should think about how to make the UX better by supporting them in atomic components.

We could do a couple of things 

1. Add support for a placeholder /loading state till we receive the xhr response (quite possible we already support it) and make sure when using bind the loading state is triggered when url swap happens

2. Provide decent usage examples of 1. in ampstart. (examples , facebook's dummy feed images)

3. Support `autoresize` on amp-list (with animated scroll if possible)

**Comment by ericlindley-g** [comment]
+1 to your first point, @lswang1618 , though in the short term amp-list is the only way to support autocomplete/sort/filter/etc—dynamic interactions that happen after the initial page load, so that creates some additional complexity. In cases where the data at load time is not highly dynamic, but the developer wants this dynamic functionality, real-data placeholders might make sense and be a seamless user experience.

**Comment by ericlindley-g** [comment]
@camelburrito Recently filed what I think is similar to your #3 here: https://github.com/ampproject/amphtml/issues/11945  Would def want to get more ideas there

**Comment by lswang1618** [comment]
Oh got it, makes sense
